sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: YB9xQQSJV1lJz9UJEdmOTe7Yq/fkJ/fHGp/zLk13lu+JgADDyjvvgYt2uoaEESQScsLoeA/2R9jlH1lnxfnaswCWt/bJxIhNHcyKsGA7RnXSDsq7D+evFLhYIWmW8JvQJe1KvgpTyPIjSkzZi8vwmV5kVVWAbDroFrJR1YOvvx+be/mf4+CXn22Rg+TDqwXebOvTX5oKLP5hS013PA49p7mIV0+JR3N4EMgM4T+byuIjrhj8F28wyR8np2Ri5U/SQry26PLPwjdU7qJdskLeRrj4l+JnpSsfW/8YHUUGib+cBIzl0INpqC/Gxe+C5YIBbAQ3IuQj3jUKMZ4PNMIfivJhVqa9jQSf30stRG7NLq+O25vYwpkiVInW/WA56/FZfm7p38c5RSYvnoZNxsaNU3x64c9VzqVd3i98M5EmjKUAQP0j+YnenRYUoPh92jzNnxw52qIsCCDatEefv2c+SO2tjDMzAiq7F9M4daz3g7EcBUY0j0VRDuXfIQLV/Ebtyy0Nelg2Uen3S4Ys2rBmIkmwamCnr0oHCaPoHShU8f7JH01rt/4HQ3jJl63lsuaayg920p+ziruaMOVSLt/s/fp4q9EmMOtwlTTiMSTuArn4i7DrDQw0AFWKYv7yOuXpZZLOdk9X8WY303YD8Ah7I5+LKtDNjtVCRYafLcIW4Wk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Tempest_1801
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy